AWSTemplateFormatVersion: '2010-09-09'
Description: "RDS for FastapiTemplate Production API"

Parameters:
  ENVIRONMENT:
    Type: String
    Default: production
    AllowedValues:
      - development
      - production
    Description: The environment for the stack (e.g., development, production).

  DBUsername:
    Type: String
    Description: The database admin username.

  DBPassword:
    Type: String
    Description: The database admin password.


Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./rds.yaml
      Parameters:
        ENVIRONMENT: !Ref ENVIRONMENT
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        VPC: !GetAtt VPCStack.Outputs.FastapiTemplateVPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2

