AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for API

Resources:
  # Create an ECR repository for the API application
  ApiECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: 'api-repository'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Remove untagged images older than 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }


Outputs:
  ApiECRRepository:
    Value: !Ref ApiECRRepository
    Description: The ECR repository for the API application.
    Export:
      Name: "ApiECRRepository"

      